### ISSUE TITLE
sshpass: command not found

### ISSUE THREAD

**Issue by DrInTech22** [hngprojects/pr-deploy#77]
```
Run cd /home/***/self-hosted-3/_work/_actions/hngprojects/pr-deploy/v1.1.8 && bash entrypoint.sh
  cd /home/***/self-hosted-3/_work/_actions/hngprojects/pr-deploy/v1.1.8 && bash entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SERVER_HOST: ***
    SERVER_USERNAME: ***
    SERVER_PASSWORD: ***
    SERVER_PORT: 22
    CONTEXT: .
    DOCKERFILE: docker/development/Dockerfile
    EXPOSED_PORT: 3000
    ENVS: 
    COMMENT: false
    REPO_URL: https://github.com/hngprojects/aivideo_fe.git
    REPO_OWNER: hngprojects
    REPO_NAME: aivideo_fe
    PR_NUMBER: 71
    PR_ACTION: synchronize
    PR_ID: pr_834861826_71
    GITHUB_TOKEN: ***
entrypoint.sh: line 7: sshpass: command not found
Error: Process completed with exit code 127.
```
The context in my case should be /dev/another/directory, but if it is added it returns `file or directory not found`.
If the context is left as '.', it works and return the error above `entrypoint.sh: line 7: sshpass: command not found`
## Steps to Reproduce:

1. Create a sample workflow with context pointing to a subdirectory.
2. Open a pull request in the repository.
3. Observe the error in the entrypoint.sh script where sshpass is called.

**Comment by Zenitugo** [comment]
New updates released. Use latest version

**Comment by DrInTech22** [comment]
1.9.1 
--> not a valid version
`main` worked fine for me though.

**Comment by Zenitugo** [comment]
1.1.9 not 1.9.1

**Comment by Zenitugo** [comment]
Ending this issue as it has been resolved

**Comment by DrInTech22** [comment]
Error: Unable to resolve action `hngprojects/pr-deploy@1.1.9`, unable to find version `1.1.9`

**Comment by Data-Bishop** [comment]
The version should be available now.
